#SITE SETTINGS
baseurl: /channelzero
exclude: ['README.md']
include: ['_pages']
permalink: /:title/

#SOCIAL
twitter: http://www.twitter.com
facebook: http://www.facebook.com
instagram: http://www.instagram.com

#lANG NAVIGATION
navi:
- name: Tour Dates
  url: /tour-dates
  class: 
- name: Band
  url: /band
  class: 
- name: Home
  url: /
  class: home
- name: Releases
  url: /releases
  class: 
- name: Media
  url: /media
  class: 