#SITE SETTINGS
baseurl: /channelzero
exclude: ['README.md']
include: ['_pages']
permalink: /:title/


#lANG NAVIGATION
navi:
- name: Tour Dates
  url: /tour-dates
- name: Band
  url: /band
- name: Home
  url: /
- name: Releases
  url: /releases
- name: Media
  url: /media