#SITE SETTINGS
baseurl: /channelzero
exclude: ['README.md']
include: ['_pages']
permalink: /:title/

#SOCIAL
twitter: http://www.twitter.com
facebook: http://www.facebook.com
instagram: http://www.instagram.com

#lANG NAVIGATION
navi:
- name: Tour Dates
  url: /tour-dates
- name: Band
  url: /band
- name: Home
  url: /
- name: Releases
  url: /releases
- name: Media
  url: /media